# Generated by Django 5.1 on 2024-08-26 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='João Silva', max_length=255)),
                ('email', models.EmailField(default='user.email@email.com', max_length=254, unique=True)),
                ('idade', models.IntegerField(default=30)),
                ('profissao', models.CharField(default='Desenvolvedor', max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
            ],
        ),
    ]
